### ISSUE TITLE
Performance degradation on massive writing

### ISSUE THREAD

**Issue by hkalina** [cockroachdb/pebble#1691]
Hello,
we are importing large amount of data (261,000,000 records) into the pebble database - we write them using Put operation.
The **performance of writes degrades** and new writes takes more and more time.
From the metrics table we see the level 0 becomes huge and it is probably the cause.

* Closing and reopening the database does not help
* Enclosing writes into batches did not help
* When we run `db.Compact([]byte{0x00}, []byte{0xFF})` in the middle of the import, it becomes fast again
* Without compact, the import takes **25 hours**
* When we run Compact +- every 1 minute, it is finished in **3 hours** (the Compacts time included)

I believe this is a performance bug of pebble.
Is there something we should check?

Thanks

Metrics (without calling Compact manually) - the level 0 grows to hundreds gigabytes:
```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         2   6.3 M       -   401 M       -       -       -       -   401 M       -       -       -     1.0
      0    387143   267 G    1.08   395 M     0 B       0     0 B       0   263 M    17 K     0 B       4     0.7
      1        25    89 M    1.35   570 M     0 B       0     0 B       0   2.3 G     804   2.3 G       1     4.2
      2       135   598 M    1.04   393 M     0 B       0   144 M      78   1.6 G     258   1.6 G       1     4.2
      3       414   5.1 G    1.00   494 M     0 B       0    10 M       4   1.8 G     155   1.8 G       1     3.8
      4      1841    45 G    0.97   368 M     0 B       0   4.0 M       1   1.4 G      60   1.4 G       1     4.0
      5     16340   397 G    0.95     0 B     0 B       0     0 B       0     0 B       0     0 B       1     0.0
      6     31725   3.4 T       -     0 B     0 B       0     0 B       0     0 B       0     0 B       1     0.0
  total    437623   4.1 T       -   401 M     0 B       0   158 M      83   7.8 G    18 K   7.2 G      10    20.0
  flush       112
compact       431   3.2 T   5.1 M       1          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype       348       0       0      83       0       0  (default, delete, elision, move, read, rewrite)
 memtbl         2   8.0 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache         0     0 B   59.8%  (score == hit-rate)
 tcache     1.9 K   1.2 M   89.8%  (score == hit-rate)
  snaps         1       - 17835168338  (score == earliest seq num)
 titers         0
 filter         -       -    0.0%  (score == utility)
```

**Comment by nicktrav** [comment]
Hi @hkalina - thanks for the report!

Mind posting the version of Pebble that you're running? It's likely that the issue you mentioned was fixed in cca64783feae4bedb035d03fdbcfd9f5c79e08e3. We typically call the situation you described as an "inverted LSM" - large amount of data sitting at the "top" of the LSM, rather than at the "bottom" - and this looks like a textbook example.

Prior to this fix, only the sublevel count determined when to trigger a compaction out of L0. You can see in your case that there are only 4 L0 sublevels (the `4` in the `r-amp` column for L0 is the L0 sublevel count), but there are a large number of files. The fix ensures that file count is also used as an input to the determination.

If you'd also be willing to describe a little more about your import workload, that might also help us identifying additional gaps that we can improve on. For example, is the data you are importing sorted vs. random?

**Comment by hkalina** [comment]
We use version cca64783feae4bedb035d03fdbcfd9f5c79e08e3, I see it is older then the fix you mention - I will retest with the latest version asap, thank you!

**Comment by hkalina** [comment]
With the new version, the performance degradation still occurs, but **after a while it fixes by itself and returns to the original (good) performance**. (We are inserting keys in ascending order, as they comes from iterator on the source server.)
Seems good enough, I am closing this.

**Comment by hkalina** [comment]
I need to reopen this issue - it still occurs even on the latest version (63d552794411) and I have been able to create a simple reproducer:

When I am inserting big bunch of data (in batches, in ascending order), the performance degrade and L0 grows.

![image](https://user-images.githubusercontent.com/3178122/180020143-6bc9a992-28ce-41a9-997e-6f3691c9e604.png)

**The state after 8 hours of inserting of 11274444800 items is:**
```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         2    12 M       -   620 G       -       -       -       -   620 G       -       -       -     1.0
      0    181557   322 G    4.21   620 G     0 B       0     0 B       0   586 G   331 K     0 B       1     0.9
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2      1939   5.4 G    4.21   183 G     0 B       0   3.2 G   1.8 K   193 G    70 K   196 G       1     1.1
      3      3931    12 G    4.22   104 G     0 B       0   145 G    56 K   127 G    38 K   136 G       1     1.2
      4     10139    27 G    4.21    33 G     0 B       0   203 G    77 K    56 G   6.4 K    57 G       1     1.7
      5      7527    62 G    4.21    96 G     0 B       0   111 G    46 K   303 G    14 K   303 G       1     3.1
      6     35504   140 G       -    45 G     0 B       0   101 G    40 K    54 G   1.6 K    60 G       1     1.2
  total    240597   568 G       -   620 G     0 B       0   563 G   221 K   1.9 T   461 K   751 G       6     3.1
  flush    110505
compact    284025   1.9 T    68 K       1          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype     63347       0       0  220678       0       0       0  (default, delete, elision, move, read, rewrite, multi-level)
 memtbl         3    16 M
zmemtbl        -1    16 E
   ztbl         0     0 B
 bcache         0     0 B    0.0%  (score == hit-rate)
 tcache         4   2.7 K   50.2%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers         2
 filter         -       -    0.0%  (score == utility)
```

The reproducer is here:
https://github.com/hkalina/pebble-benchmark/blob/master/main.go

Is it possible to improve the performance of imports of big amounts of data somehow?
Thanks!

**Comment by nicktrav** [comment]
Thanks for the follow-up, @hkalina. It appears you're hitting the same issue as before, i.e. "inverted LSM". Compactions look like they are not keeping up, and as a result L0 will continue to fill up (a single sublevel, as your workload is performing sequential writes).

The `num-in-progress` value is `1`, indicating that only a single compaction is running. Looking at your code, [you're using the defaults, which will limit compaction concurrency to one](https://github.com/cockroachdb/pebble/blob/63d5527944113188fe042ae4d284fd1bd76f2df1/options.go#L630-L635).

To begin with, you might try raising that value. For comparison, Cockroach uses a value of three, which is typically sufficient for most. If you have a write heavy workload, and have the CPU and disk bandwidth / IOPs (both reads and writes), you could try upping that value even more.

If you're interested, [here are the default Pebble options that Cockroach uses](https://github.com/cockroachdb/cockroach/blob/a3039fe628f2ab7c5fba31a30ba7bc7c38065230/pkg/storage/pebble.go#L483).

**Comment by hkalina** [comment]
Thank you, @nicktrav !
I have set the `MaxConcurrentCompactions` option to 10 and now no inverted LSM occures :+1: 

Now, after 5 hours of inserting 12121600000 items (inserting faster by 72%), the LSM is OK.
I am going to experiment to find the best value of the option for our purpose, but the issue seems resolved.
Thank you very much!

**Comment by hsanjuan** [comment]
I hit a similar issues:

```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1     0 B       -     0 B       -       -       -       -     0 B       -       -       -     0.0
      0    268518   633 G    4.69     0 B     0 B       0     0 B       0     0 B       0     0 B     880     0.0
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2      4480    46 G    4.67    62 G     0 B       0     0 B       0   1.2 T   120 K   1.2 T       1    20.1
      3      6528    68 G    4.68    40 G     0 B       0    14 G   1.6 K    63 G   6.4 K    74 G       1     1.6
      4      6024    97 G    4.68    31 G     0 B       0    11 G   1.2 K    50 G   2.7 K    63 G       1     1.6
      5      4406   140 G    0.91    24 G     0 B       0   4.7 M       4    48 G   1.2 K    59 G       1     2.0
      6      4283   166 G       -     0 B     0 B       0     0 B       0     0 B       0     0 B       1     0.0
  total    294239   1.1 T       -     0 B     0 B       0    26 G   2.8 K   1.4 T   130 K   1.4 T     885     0.0
  flush         0
compact     10095   4.1 T   7.5 G       3          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype      7320       0       0    2775       0       0       0  (default, delete, elision, move, read, rewrite, multi-level)
 memtbl         1   256 K
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache     591 K   4.7 G    0.1%  (score == hit-rate)
 tcache      33 K    21 M   25.6%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers        10
 filter         -       -  100.0%  (score == utility)
```

I don't think setting [L0StopWritesThreshold to 1000 like CockroachDB](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/pebble.go#L556) was a good idea since my r-amp went up exactly to that. I stopped writes but it is going down very very slowly. Is there a way to speed this up? I have MaxCompactions set to 10.

Another weird thing is Level 1 being empty, just like in the stats that were posted above. Why?

**Comment by nicktrav** [comment]
> I have MaxCompactions set to 10.

I assume you're talking about `MaxConcurrentCompactions`? It looks like from the above you only have 3 compactions in flight. Given the amount of compaction debt in this LSM, I'd expect more concurrent compactions.

Given there's a lot of debt in L0, you could also take a look at `L0CompactionConcurrency` too and see if you can tweak that multiplier to get more concurrency. Here's a relevant comment:

https://github.com/cockroachdb/pebble/blob/e9a8c4ad65c540ee5a7f995fbc87bded62a712dc/compaction_picker.go#L1146-L1153

**Comment by hsanjuan** [comment]
> It looks like from the above you only have 3 compactions

Normally there are 10 running. I don't know if it helps, but the cpuprofile shows the following:

![pprof001](https://user-images.githubusercontent.com/1027022/223425961-008bcf24-62c7-440c-8066-fe5634eff8c5.svg)

I'm guessing working with so many files becomes an issue when compacting and slows the process down to a crawl which gets better as r-amp goes down.

**Comment by hsanjuan** [comment]
@nicktrav any idea why L1 is unused?  I have 2 nodes which are like that, even though the sizes of the other levels are looking fine (but nodes are constantly ingesting data).

**Comment by jbowens** [comment]
@hsanjuan Which levels are open is a function of the database size. I forget how the threshold is calculated, but if you added more data eventually L1 will open.

**Comment by jbowens** [comment]
I think you should probably reduce your stop writes threshold. 250k files in L0 is far too many and will slow compaction picking out of L0 and flushes. It may appear to be faster initially with a higher stop writes threshold, but you’ll build up an intractable amount of compaction debt.

**Comment by hsanjuan** [comment]
Well, yes I reduced L0StopWritesThreshold to 12. I'm not sure why CockroachDB's uses 1000, but it seems very dangerous. On the plus side, after 2 days the compaction debt is gone and I can continue ingesting.

**Comment by jbowens** [comment]
I’m referring to the MemtableStopWritesThreshold: https://github.com/cockroachdb/pebble/blob/1c38c4cb89d45afe8092b886ce6ddef7b52f19f3/options.go#L753

**Comment by hsanjuan** [comment]
I have that set to 30. I have so much RAM and for me is ok that memtables grow and queue. L0StopWritesThreshold is what put a stop when r-amp reached 1000 (and what keeps things at an acceptable limit now). Given I'm writing all the time I am always going to hit the limit and I am always going to be writing to L0 as much as possible, so limiting the memtables size won't prevent me from hammering the disk enough for compactions to pile and pile, I think.

**Comment by jbowens** [comment]
You can use either of the stop writes threshold settings, or application-level queueing, to avoid overloading L0. `L0StopWritesThreshold` limits terms of sublevels, which is not equal to the number of files in L0. Typically you don't want L0 sublevels to grow to avoid making reads more expensive. If you have no reads, L0 sublevels don't matter—what matters is the number of files. In any case, 250k files in L0 makes constructing new versions of the LSM expensive and will slow compactions and new flushes.

**Comment by hsanjuan** [comment]
But when writes are stopped because too many sublevels exist, that allows compactions to resume and the number of files is reduced accordingly. Is it possible to have many files without many sublevels?

**Comment by jbowens** [comment]
> Is it possible to have many files without many sublevels?

Yes. When sublevels work well, there should be an order of magnitude or two fewer sublevels than files. Depending on the workload, you can result with several orders of magnitude fewer sublevels than files.
